# Generated by Django 3.2.13 on 2022-07-22 05:34

from django.db import migrations

def fill_with_data_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >=2010:
            flat.new_building = True
            flat.save

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_with_data_construction_year),
    ]

