# Generated by Django 3.2.13 on 2022-07-22 06:00

from django.db import migrations

def fill_with_data_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    i=0
    for flat in Flat.objects.all():
        if flat.construction_year >=2010:
            i=i+1
            flat.new_building = True
            flat.save
    print(i)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220722_0834'),
    ]

    operations = [
        migrations.RunPython(fill_with_data_construction_year),
    ]
