# Generated by Django 3.2.13 on 2022-07-22 06:08

from django.db import migrations

def fill_with_data_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    i=0
    for flat in Flat.objects.all():
        flat.new_building = True
        flat.save

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220722_0900'),
    ]

    operations = [
    ]
