# Generated by Django 3.2.13 on 2022-07-22 06:22

from django.db import migrations

def get_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = True
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20220722_0912'),
    ]

    operations = [
        migrations.RunPython(get_new_building),
    ]
