# Generated by Django 3.2.13 on 2022-07-23 17:58

from django.db import migrations

def get_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.created_at.year > 2014:
            flat.new_building = True
        flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = None
        flat.save()   

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220722_0922'),
    ]

    operations = [
        migrations.RunPython(move_backward),
    ]
