# Generated by Django 3.2.13 on 2022-07-23 18:30

from django.db import migrations


def get_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.new_building = (flat.construction_year > 2014)
        flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.new_building = None
        flat.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(get_new_building),
    ]
