# Generated by Django 3.2.13 on 2022-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20220828_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='ФИО владельца'),
        ),
    ]
