# Generated by Django 3.2.13 on 2022-08-28 13:31

from django.db import migrations

def get_flat_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        flat_owner = Owner.objects.get(name=flat.owner, phonenumber=flat.owners_phonenumber)
        flat_owner.flats.add(flat)
        flat_owner.save


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        flat_owner = Owner.objects.get(name=flat.owner, phonenumber=flat.owners_phonenumber)
        flat_owner.flats = None
        flat_owner.save

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_owner_name'),
    ]

    operations = [
        migrations.RunPython(get_flat_owners)
    ]
