# Generated by Django 3.2.13 on 2022-08-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20220828_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
