# Generated by Django 3.2.13 on 2022-09-04 18:54

from django.db import migrations

def change_none_to_empty_string(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.filter(name=None):
        owner.name = ''
        owner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20220828_1805'),
    ]

    operations = [
        migrations.RunPython(change_none_to_empty_string)
    ]
