# Generated by Django 3.2.13 on 2022-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
